# Generated by Django 3.0.8 on 2020-08-03 17:13

from django.db import migrations, models
import shortener.validators


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0002_auto_20200803_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rezseclyurl',
            name='url',
            field=models.CharField(max_length=254, validators=[shortener.validators.validate_url]),
        ),
    ]
